name = "site"
type = "javascript"
account_id = "31b6f0f07166da218b3b9b22a2414860"
workers_dev = true
route = ""
zone_id = ""


# environment configuration
[env.development]
name="devsite"
route="devsite.jwrc.me"

[env.production]
name="site"
route="site.jwrc.me"

