on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: test
        run: sudo chown -R $USER:$USER /home/github/actions-runner/work/JamesWRC.github.io
      - name: Check syntax
        run: sudo apt-get update; sudo apt-get install sed
      - name:
        run: pwd;sudo chmod +x /home/runner/work/JamesWRC.github.io/JamesWRC.github.io/fixLinks.sh;sh /home/runner/work/JamesWRC.github.io/JamesWRC.github.io/fixLinks.sh
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.PERSONAL_SITE_CF_API_TOKEN }}
          environment: 'production'
