on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: test
        run: echo ${{ github.workspace }}
      - name: Check syntax
        run: sudo apt-get update; sudo apt-get install sed
      - name:
        run: pwd;sudo chmod +x ${{ github.workspace }}/fixLinks.sh;sh ${{ github.workspace }}/fixLinks.sh
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.PERSONAL_SITE_CF_API_TOKEN }}
          environment: 'production'
